### ISSUE TITLE
Build fails because FAAC cannot be downloaded

### ISSUE THREAD

**Issue by randomshinichi** [fastogt/fastocloud#21]
Sourceforge is being DDOSed which is why FAAC could not be downloaded.

Still, such an error should not cause the build process to fail.

```
Building wheels for collected packages: iso-639
  Running setup.py bdist_wheel for iso-639: started
  Running setup.py bdist_wheel for iso-639: finished with status 'error'
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-1xra352g/iso-639/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmphsp6hd0spip-wheel- --python-tag cp35:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for iso-639
  Running setup.py clean for iso-639
Failed to build iso-639
Installing collected packages: PySocks, urllib3, idna, chardet, requests, pycryptodome, iso-639, iso3166, six, isodate, websocket-client, streamlink
  Running setup.py install for iso-639: started
    Running setup.py install for iso-639: finished with status 'done'
Successfully installed PySocks-1.7.1 chardet-3.0.4 idna-2.8 iso-639-0.4.5 iso3166-1.0 isodate-0.6.0 pycryptodome-3.9.0 requests-2.22.0 six-1.12.0 streamlink-1.2.0 urllib3-1.25.6 websocket-client-0.56.0
Collecting speedtest-cli
  Downloading https://files.pythonhosted.org/packages/c4/44/dfebd38c5fb35aae0a7279e2a3ffe33ca65edb449a586b93addc8d409a71/speedtest_cli-2.1.2-py2.py3-none-any.whl
Installing collected packages: speedtest-cli
Successfully installed speedtest-cli-2.1.2
Build request for platform: linux(x86_64) created
Downloading: faac-1.29.9.2.tar.gz Bytes: 746
Extracting: /usr/src/fastocloud/build/build_linux_env/faac-1.29.9.2.tar.gz
Traceback (most recent call last):
  File "./build_env.py", line 657, in <module>
    request.build_faac()
  File "./build_env.py", line 285, in build_faac
    self._download_and_build_via_configure(FAAC_URL, compiler_flags)
  File "/usr/local/lib/python3.5/dist-packages/pyfastogt-1.1.0-py3.5.egg/pyfastogt/build_utils.py", line 342, in _download_and_build_via_configure
  File "/usr/local/lib/python3.5/dist-packages/pyfastogt-1.1.0-py3.5.egg/pyfastogt/utils.py", line 117, in extract_file
  File "/usr/local/lib/python3.5/dist-packages/pyfastogt-1.1.0-py3.5.egg/pyfastogt/utils.py", line 115, in extract_file
  File "/usr/lib/python3.5/tarfile.py", line 1564, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
ERROR: Service 'iptv' failed to build: The command '/bin/sh -c set -ex;   BUILD_DEPS='ca-certificates git python3 python3-pip';   PREFIX=/usr/local;   apt-get update;   apt-get install -y $BUILD_DEPS --no-install-recommends;     pip3 install setuptools;   PYFASTOGT_DIR=/usr/src/pyfastogt;   mkdir -p $PYFASTOGT_DIR && git clone https://github.com/fastogt/pyfastogt $PYFASTOGT_DIR && cd $PYFASTOGT_DIR && python3 setup.py install;     PROJECT_DIR=/usr/src/fastocloud;   mkdir -p $PROJECT_DIR && git clone https://github.com/fastogt/fastocloud $PROJECT_DIR && cd $PROJECT_DIR && git submodule update --init --recursive;   cd $PROJECT_DIR/build && ./build_env.py --prefix=$PREFIX;   LICENSE_KEY="$(license_gen --machine-id)";   cd $PROJECT_DIR/build && PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig python3 build.py release $LICENSE_KEY 1 $PREFIX; rm -rf $PYFASTOGT_DIR $PROJECT_DIR # && apt-get purge -y --auto-remove $BUILD_DEPS' returned a non-zero code: 1
```

**Comment by topilski** [comment]
Hi @randomshinichi , thank you will fix

**Comment by topilski** [comment]
fixed
